// AUTO-DECOMPILED from br_gamemode.amx
// Source module: include/lib_m_crzones.inc
// Functions: 2

// AMX 0x76d0
stock GetCityName(size)
{
    // --- line 60 ---
    // --- line 62 ---
    // goto 0x76f8
    // load var_-4
    // _ = -1;
    // goto 0x7984
    // --- line 63 ---
    // load var_12
    // _ = 19732;
    // load var_-4
    func_0x358(8);
    if (!_) {} // goto 0x77fc
    // load var_12
    // _ = 19732;
    // load var_-4
    func_0x44c(8);
    if (!_) {} // goto 0x77fc
    // goto 0x7800
    if (!_) {} // goto 0x790c
    // load var_16
    // _ = 19732;
    // load var_-4
    func_0x358(8);
    if (!_) {} // goto 0x78f0
    // load var_16
    // _ = 19732;
    // load var_-4
    func_0x44c(8);
    if (!_) {} // goto 0x78f0
    // goto 0x78f4
    if (!_) {} // goto 0x790c
    // goto 0x7910
    if (!_) {} // goto 0x797c
    // --- line 64 ---
    // _ = 19732;
    // load var_-4
    strunpack(12, var_20);
    // stack 16
    // stack 4
    return 1;
    // goto 0x76ec
    // stack 4
    // --- line 67 ---
    return 1;
}

// AMX 0x799c
stock GetAreaName(size)
{
    // --- line 74 ---
    // --- line 76 ---
    // goto 0x79c4
    // load var_-4
    // _ = -1;
    // goto 0x7c50
    // --- line 77 ---
    // load var_12
    // _ = 20572;
    // load var_-4
    func_0x358(8);
    if (!_) {} // goto 0x7ac8
    // load var_12
    // _ = 20572;
    // load var_-4
    func_0x44c(8);
    if (!_) {} // goto 0x7ac8
    // goto 0x7acc
    if (!_) {} // goto 0x7bd8
    // load var_16
    // _ = 20572;
    // load var_-4
    func_0x358(8);
    if (!_) {} // goto 0x7bbc
    // load var_16
    // _ = 20572;
    // load var_-4
    func_0x44c(8);
    if (!_) {} // goto 0x7bbc
    // goto 0x7bc0
    if (!_) {} // goto 0x7bd8
    // goto 0x7bdc
    if (!_) {} // goto 0x7c48
    // --- line 78 ---
    // _ = 20572;
    // load var_-4
    strunpack(12, var_20);
    // stack 16
    // stack 4
    return 1;
    // goto 0x79b8
    // stack 4
    // --- line 81 ---
    return 1;
}
